#!/bin/bash

echo "🔑 GitHub SSH Key Setup"
echo "======================"
echo ""
echo "Your SSH public key has been generated:"
echo ""
cat ~/.ssh/id_ed25519_github.pub
echo ""
echo "📋 NEXT STEPS:"
echo "=============="
echo ""
echo "1. Copy the SSH key above (starts with 'ssh-ed25519')"
echo ""
echo "2. Go to GitHub: https://github.com/settings/keys"
echo ""
echo "3. Click 'New SSH key'"
echo ""
echo "4. Give it a title: 'TimeMachine Project - MacBook'"
echo ""
echo "5. Paste the key in the 'Key' field"
echo ""
echo "6. Click 'Add SSH key'"
echo ""
echo "7. Run this command to test:"
echo "   ssh -T git@github.com"
echo ""
echo "8. When prompted, type 'yes' to continue"
echo ""
echo "✅ After adding the key, run:"
echo "   ./scripts/sync-with-github.sh"
echo ""
echo "🎯 This will complete TASK-001!"
